# Generated by Django 3.0.5 on 2020-05-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200509_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='code',
        ),
    ]
