# Generated by Django 3.0.5 on 2020-05-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_staff_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='code',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
    ]
